### ISSUE TITLE
feature: Support blockwise Visual mode

### ISSUE THREAD

**Issue by CAESIUS-TIM** [ai-smith/nvim-ui-modes#1]
`:help visual-block`

> With CTRL-V (blockwise Visual mode) the highlighted text will be a rectangle
between start position and the cursor.  However, some operators work on whole
lines anyway (see the list below).  The change and substitute operators will
delete the highlighted text and then start insertion at the top left
position.

![v_V_C-v](https://github.com/user-attachments/assets/4dea07af-df2d-4e62-8a5c-951aed71123b)

- [x] charwise-visual
- [x] linewise-visual
- [x] blockwise-visual

**Comment by ai-smith** [comment]
You should write these notes to the vscode-neovim plugin. My plugin is only responsible for changing colors of user interface elements when changing modes.
